[package]
name = "dpiproxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dnsoverhttps = "0.6.0"
httparse = "1.8.0"
tokio = { version = "1.35.1", features = ["full"] }
